// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD77a3ygmsa6NdCfRLuUQGY6gtWsUxFMc4',
    appId: '1:430644823856:web:4099472d41c5d783bbeaf5',
    messagingSenderId: '430644823856',
    projectId: 'stryke-30afd',
    authDomain: 'stryke-30afd.firebaseapp.com',
    storageBucket: 'stryke-30afd.firebasestorage.app',
    measurementId: 'G-ZLWL3QVXZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdgtoVYXLYG2r_2K-z_RZLdcfRS_sTNJo',
    appId: '1:430644823856:android:98104ea679d03c32bbeaf5',
    messagingSenderId: '430644823856',
    projectId: 'stryke-30afd',
    storageBucket: 'stryke-30afd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdwO-rrp0iYTQwx_TPnJA8fYesSIOe0-8',
    appId: '1:430644823856:ios:6c4e8b39c6b62079bbeaf5',
    messagingSenderId: '430644823856',
    projectId: 'stryke-30afd',
    storageBucket: 'stryke-30afd.firebasestorage.app',
    iosBundleId: 'com.example.strykeMain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdwO-rrp0iYTQwx_TPnJA8fYesSIOe0-8',
    appId: '1:430644823856:ios:6c4e8b39c6b62079bbeaf5',
    messagingSenderId: '430644823856',
    projectId: 'stryke-30afd',
    storageBucket: 'stryke-30afd.firebasestorage.app',
    iosBundleId: 'com.example.strykeMain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD77a3ygmsa6NdCfRLuUQGY6gtWsUxFMc4',
    appId: '1:430644823856:web:b781e8a535bfa752bbeaf5',
    messagingSenderId: '430644823856',
    projectId: 'stryke-30afd',
    authDomain: 'stryke-30afd.firebaseapp.com',
    storageBucket: 'stryke-30afd.firebasestorage.app',
    measurementId: 'G-4XQRFFKHPC',
  );
}
