name: test_app
description: "A new Flutter Pizza"
publish_to: 'none'
version: 0.1.0

environment:
  sdk:  '>=3.2.3 <4.0.0'

dependencies:
  multicast_dns: ^0.3.2
  firebase_auth: ^5.5.1
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.5
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  slide_to_act: ^2.0.2
  flutter_launcher_icons: ^0.13.1


  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  intl: ^0.20.2

  shared_preferences: ^2.5.3
  geolocator: ^10.0.0
  firebase_messaging: ^15.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  multicast_dns: ^0.3.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.png
    - assets/images/app_icon.png