name: test_app
description: "A new Flutter Pizza"
publish_to: 'none'
version: 0.1.0

environment:
  sdk:  '>=3.2.3 <4.0.0'

dependencies:
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.7.0
  google_fonts: ^6.2.1
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  cupertino_icons: ^1.0.0


  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  user_repository:
    path: packages/user_repository


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true