name: test_app
description: "A new Flutter Pizza"
publish_to: 'none'
version: 0.1.0

environment:
  sdk:  '>=3.2.3 <4.0.0'

dependencies:
  firebase_auth: ^4.20.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.7.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0


  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.png